server:
  port: 8081
  
spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
#      table-prefix: LON_
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: STUDENT
    password: 123456